/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    organizations: Organization;
    games: Game;
    teams: Team;
    members: Member;
    tenures: Tenure;
    matches: Match;
    achievements: Achievement;
    brands: Brand;
    founders: Founder;
    pages: Page;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    organizations: {
      roster: 'tenures';
    };
    members: {
      tenures: 'tenures';
    };
  };
  collectionsSelect: {
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    games: GamesSelect<false> | GamesSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    tenures: TenuresSelect<false> | TenuresSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    achievements: AchievementsSelect<false> | AchievementsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    founders: FoundersSelect<false> | FoundersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    homepage: Homepage;
    'featured-event': FeaturedEvent;
    'page-intros': PageIntro;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'featured-event': FeaturedEventSelect<false> | FeaturedEventSelect<true>;
    'page-intros': PageIntrosSelect<false> | PageIntrosSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  shortName?: string | null;
  slug: string;
  logo?: (number | null) | Media;
  banner?: (number | null) | Media;
  founded?: number | null;
  description?: string | null;
  website?: string | null;
  twitter?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  /**
   * Hex accent used on the public profile.
   */
  accentHex?: string | null;
  isVerified?: boolean | null;
  /**
   * Everyone who has had a stint at this org (from Tenures).
   */
  roster?: {
    docs?: (number | Tenure)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * A member’s time at one org. Usually edited from the Member screen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenures".
 */
export interface Tenure {
  id: number;
  title?: string | null;
  member: number | Member;
  /**
   * Family org for this stint. Leave blank for an outside club (fill External club below).
   */
  org?: (number | null) | Organization;
  /**
   * Name of a NON-family club (e.g. GodLike) when the stint wasn’t at a family org.
   */
  externalOrg?: string | null;
  /**
   * Optional link for the external club (Liquipedia/official).
   */
  externalUrl?: string | null;
  /**
   * Role during THIS stint.
   */
  role: 'PLAYER' | 'CREATOR' | 'COACH' | 'ANALYST' | 'MANAGER' | 'OWNER';
  /**
   * Squad/game in that org (optional).
   */
  team?: (number | null) | Team;
  /**
   * Entry.
   */
  joinedAt: string;
  /**
   * Exit — leave blank if still current.
   */
  leftAt?: string | null;
  /**
   * Founded THIS org (day-one).
   */
  isFounding?: boolean | null;
  /**
   * Context / fuzzy-date note (optional).
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  /**
   * Show on the homepage “Featured roster”.
   */
  featured?: boolean | null;
  ign: string;
  realName?: string | null;
  slug: string;
  /**
   * Current/primary role. Role per stint lives on each Tenure.
   */
  role: 'PLAYER' | 'CREATOR' | 'COACH' | 'ANALYST' | 'MANAGER' | 'OWNER';
  /**
   * Current/primary org. Full history lives under Affiliations.
   */
  org: number | Organization;
  /**
   * In-game role — e.g. IGL, Fragger, Duelist, Support.
   */
  position?: string | null;
  avatar?: (number | null) | Media;
  banner?: (number | null) | Media;
  bio?: string | null;
  country?: string | null;
  isVerified?: boolean | null;
  isActive?: boolean | null;
  /**
   * Joined the S8UL FAMILY on… (family-level; per-org dates live on Tenures).
   */
  joinedAt?: string | null;
  /**
   * Each stint at a family org — entry/exit, role, founding. Add a row per org/spell.
   */
  tenures?: {
    docs?: (number | Tenure)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Current squads (quick display). Historical squads live on each tenure.
   */
  teams?: (number | Team)[] | null;
  /**
   * Add one row per platform. Followers are optional.
   */
  socials?:
    | {
        platform:
          | 'YOUTUBE'
          | 'INSTAGRAM'
          | 'TWITTER'
          | 'TWITCH'
          | 'FACEBOOK'
          | 'DISCORD'
          | 'TIKTOK'
          | 'SNAPCHAT'
          | 'WEBSITE'
          | 'OTHER';
        handle?: string | null;
        url: string;
        /**
         * Follower / subscriber count.
         */
        followers?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * List milestones oldest → newest (start to today).
   */
  career?:
    | {
        year: string;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Add one row per channel for creators with more than one (e.g. Main + Shorts). If empty, the YouTube handle in Social presence is used.
   */
  youtubeChannels?:
    | {
        label: string;
        handle: string;
        /**
         * Shown first.
         */
        primary?: boolean | null;
        /**
         * Video URL or ID to feature for this channel.
         */
        featuredVideo?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Featured video for the single/primary channel (optional — defaults to the latest upload).
   */
  featuredYoutubeVideo?: string | null;
  /**
   * Paste public Instagram post URLs to embed (e.g. 5–10).
   */
  instagramPosts?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDesc?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  name: string;
  slug: string;
  org: number | Organization;
  game: number | Game;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games".
 */
export interface Game {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  bgImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: number;
  opponent: string;
  status: 'LIVE' | 'UPCOMING' | 'COMPLETED';
  /**
   * e.g. BGMI — Group Stage
   */
  competition?: string | null;
  game?: string | null;
  event?: string | null;
  startsAt: string;
  scoreS8ul?: number | null;
  scoreOpponent?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements".
 */
export interface Achievement {
  id: number;
  title: string;
  slug: string;
  year: string;
  /**
   * e.g. EWC, BGMI, Awards
   */
  category?: string | null;
  description?: string | null;
  /**
   * Team trophy (shown on the org timeline) or an individual award (shown on the player).
   */
  type: 'Team' | 'Individual';
  /**
   * Result — leave blank for awards (e.g. Personality of the Year).
   */
  placement?: ('CHAMPION' | 'RUNNER_UP' | 'TOP_3' | 'QUALIFIED') | null;
  /**
   * Which family org won it (optional).
   */
  org?: (number | null) | Organization;
  /**
   * BGMI / Valorant — blank for non-game awards.
   */
  game?: (number | null) | Game;
  /**
   * Precise squad, e.g. iQOOSouL BGMI (optional).
   */
  team?: (number | null) | Team;
  /**
   * Who earned it — the winning roster (Team) or one person (Individual). Empty for org milestones.
   */
  members?: (number | Member)[] | null;
  /**
   * Higher = shown first. Tip: use the year (e.g. 2026) plus a tiebreaker.
   */
  sortKey?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sponsors and brand partners shown on the Partners hub and org pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  /**
   * Brand/company — e.g. iQOO, AMD, Monster Energy.
   */
  name: string;
  slug: string;
  /**
   * Brand mark.
   */
  logo?: (number | null) | Media;
  category: 'TITLE' | 'SPONSOR' | 'AMBASSADOR' | 'COLLABORATION' | 'MERCH' | 'CAMPAIGN' | 'EVENT';
  status: 'ACTIVE' | 'PAST';
  /**
   * Which family org(s) this deal involves (at least one).
   */
  orgs: (number | Organization)[];
  /**
   * Players/creators/owners doing the brand work (optional).
   */
  members?: (number | Member)[] | null;
  /**
   * Scope to a squad — e.g. the squad a Title brand names (iQOO → Team iQOOSouL).
   */
  team?: (number | null) | Team;
  /**
   * Scope to a discipline when there’s no single team.
   */
  game?: (number | null) | Game;
  /**
   * Deal start.
   */
  startDate?: string | null;
  /**
   * Deal end — blank if ongoing.
   */
  endDate?: string | null;
  /**
   * The partnership in a line or two.
   */
  description?: string | null;
  url?: string | null;
  /**
   * Highlight on the hub (wide card).
   */
  featured?: boolean | null;
  /**
   * Higher = shown first.
   */
  sortKey?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "founders".
 */
export interface Founder {
  id: number;
  name: string;
  alias?: string | null;
  slug: string;
  role: string;
  bio?: string | null;
  photo?: (number | null) | Media;
  /**
   * Lower = shown first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Custom pages you can create without code. They live at /your-slug.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path, e.g. "privacy" → /privacy. Lowercase, no spaces.
   */
  slug: string;
  /**
   * Uncheck to hide the page from the site.
   */
  published?: boolean | null;
  headerKicker?: string | null;
  /**
   * Line under the page title.
   */
  subtitle?: string | null;
  /**
   * Build the page from sections — add, reorder and mix any of these blocks.
   */
  layout?:
    | (
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            kicker?: string | null;
            heading: string;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'section';
          }
        | {
            items?:
              | {
                  value: number;
                  label: string;
                  /**
                   * Abbreviate big numbers.
                   */
                  compact?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            primaryLabel?: string | null;
            primaryHref?: string | null;
            secondaryLabel?: string | null;
            secondaryHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            kicker?: string | null;
            heading?: string | null;
            source?: ('featured' | 'all') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'roster';
          }
        | {
            kicker?: string | null;
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'foundersBlock';
          }
        | {
            image: number | Media;
            caption?: string | null;
            fullBleed?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
      )[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  metaTitle?: string | null;
  metaDesc?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('owner' | 'admin' | 'editor' | 'contributor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'games';
        value: number | Game;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'tenures';
        value: number | Tenure;
      } | null)
    | ({
        relationTo: 'matches';
        value: number | Match;
      } | null)
    | ({
        relationTo: 'achievements';
        value: number | Achievement;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'founders';
        value: number | Founder;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  slug?: T;
  logo?: T;
  banner?: T;
  founded?: T;
  description?: T;
  website?: T;
  twitter?: T;
  instagram?: T;
  youtube?: T;
  accentHex?: T;
  isVerified?: T;
  roster?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games_select".
 */
export interface GamesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  bgImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  org?: T;
  game?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  featured?: T;
  ign?: T;
  realName?: T;
  slug?: T;
  role?: T;
  org?: T;
  position?: T;
  avatar?: T;
  banner?: T;
  bio?: T;
  country?: T;
  isVerified?: T;
  isActive?: T;
  joinedAt?: T;
  tenures?: T;
  teams?: T;
  socials?:
    | T
    | {
        platform?: T;
        handle?: T;
        url?: T;
        followers?: T;
        id?: T;
      };
  career?:
    | T
    | {
        year?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  youtubeChannels?:
    | T
    | {
        label?: T;
        handle?: T;
        primary?: T;
        featuredVideo?: T;
        id?: T;
      };
  featuredYoutubeVideo?: T;
  instagramPosts?:
    | T
    | {
        url?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDesc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenures_select".
 */
export interface TenuresSelect<T extends boolean = true> {
  title?: T;
  member?: T;
  org?: T;
  externalOrg?: T;
  externalUrl?: T;
  role?: T;
  team?: T;
  joinedAt?: T;
  leftAt?: T;
  isFounding?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  opponent?: T;
  status?: T;
  competition?: T;
  game?: T;
  event?: T;
  startsAt?: T;
  scoreS8ul?: T;
  scoreOpponent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements_select".
 */
export interface AchievementsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  year?: T;
  category?: T;
  description?: T;
  type?: T;
  placement?: T;
  org?: T;
  game?: T;
  team?: T;
  members?: T;
  sortKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  category?: T;
  status?: T;
  orgs?: T;
  members?: T;
  team?: T;
  game?: T;
  startDate?: T;
  endDate?: T;
  description?: T;
  url?: T;
  featured?: T;
  sortKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "founders_select".
 */
export interface FoundersSelect<T extends boolean = true> {
  name?: T;
  alias?: T;
  slug?: T;
  role?: T;
  bio?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  published?: T;
  headerKicker?: T;
  subtitle?: T;
  layout?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        section?:
          | T
          | {
              kicker?: T;
              heading?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    compact?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              primaryLabel?: T;
              primaryHref?: T;
              secondaryLabel?: T;
              secondaryHref?: T;
              id?: T;
              blockName?: T;
            };
        roster?:
          | T
          | {
              kicker?: T;
              heading?: T;
              source?: T;
              id?: T;
              blockName?: T;
            };
        foundersBlock?:
          | T
          | {
              kicker?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              image?: T;
              caption?: T;
              fullBleed?: T;
              id?: T;
              blockName?: T;
            };
      };
  body?: T;
  metaTitle?: T;
  metaDesc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Brand name, wordmark, tagline and footer details.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  /**
   * The accent word after the logo (e.g. “VERSE”).
   */
  wordmarkSuffix?: string | null;
  /**
   * Shown in the intro curtain and footer baseline.
   */
  tagline?: string | null;
  /**
   * Footer location line.
   */
  location?: string | null;
  /**
   * Name in the © line.
   */
  copyrightName?: string | null;
  /**
   * The org names shown in the footer “universe of” strip.
   */
  familyOrgs?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Home/default page title.
   */
  metaTitleDefault?: string | null;
  /**
   * Title pattern for sub-pages. %s = the page title.
   */
  metaTitleTemplate?: string | null;
  metaDescription?: string | null;
  /**
   * Search keywords.
   */
  keywords?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  twitterHandle?: string | null;
  /**
   * Browser theme color (hex).
   */
  themeColor?: string | null;
  schemaOrgName?: string | null;
  schemaLocation?: string | null;
  schemaAlternateNames?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Header + footer menus and social links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Top-bar links, left to right.
   */
  header?:
    | {
        label: string;
        /**
         * e.g. /players or https://…
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Grouped link columns in the footer.
   */
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  social?:
    | {
        platform: 'YouTube' | 'Instagram' | 'Twitter' | 'Twitch' | 'Facebook' | 'Discord' | 'TikTok' | 'Website';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Small line in the footer baseline. Defaults to “Where legends live.”
   */
  footerTagline?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hero, stat labels, section headings and CTA copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Small line above the headline.
   */
  heroEyebrow?: string | null;
  /**
   * One row per line of the big headline. Tick “accent” to gradient it.
   */
  heroHeadline?:
    | {
        word: string;
        accent?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Faint oversized watermark behind the hero.
   */
  heroGhostText?: string | null;
  heroSubtitle?: string | null;
  heroCtaLabel?: string | null;
  heroCtaHref?: string | null;
  statMembersLabel?: string | null;
  statMembersValue?: string | null;
  statOrgsLabel?: string | null;
  statOrgsValue?: string | null;
  statTitlesLabel?: string | null;
  statTitlesValue?: string | null;
  statReachLabel?: string | null;
  statReachValue?: string | null;
  orgsKicker?: string | null;
  orgsTitle?: string | null;
  rosterKicker?: string | null;
  rosterTitle?: string | null;
  ctaEyebrow?: string | null;
  ctaTitle?: string | null;
  ctaPrimaryLabel?: string | null;
  ctaPrimaryHref?: string | null;
  ctaSecondaryLabel?: string | null;
  ctaSecondaryHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The headline event band (countdown + copy).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-event".
 */
export interface FeaturedEvent {
  id: number;
  kicker?: string | null;
  title?: string | null;
  /**
   * Full event name shown on the card.
   */
  eventName?: string | null;
  /**
   * Index label (top-right).
   */
  dateRangeLabel?: string | null;
  location?: string | null;
  prize?: string | null;
  /**
   * Countdown target.
   */
  startsAt?: string | null;
  /**
   * Prefix before each fixture opponent (e.g. “S8UL · …”).
   */
  teamPrefix?: string | null;
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Headers for the Players / Orgs / EWC / Honours / About pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-intros".
 */
export interface PageIntro {
  id: number;
  players?: {
    kicker?: string | null;
    title?: string | null;
    subtitle?: string | null;
  };
  orgs?: {
    kicker?: string | null;
    title?: string | null;
    subtitle?: string | null;
  };
  ewc?: {
    kicker?: string | null;
    subtitle?: string | null;
  };
  achievements?: {
    kicker?: string | null;
    title?: string | null;
    subtitle?: string | null;
  };
  founders?: {
    kicker?: string | null;
    title?: string | null;
  };
  about?: {
    kicker?: string | null;
    title?: string | null;
    subtitle?: string | null;
    lead?: string | null;
    body?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  wordmarkSuffix?: T;
  tagline?: T;
  location?: T;
  copyrightName?: T;
  familyOrgs?:
    | T
    | {
        name?: T;
        id?: T;
      };
  metaTitleDefault?: T;
  metaTitleTemplate?: T;
  metaDescription?: T;
  keywords?:
    | T
    | {
        value?: T;
        id?: T;
      };
  twitterHandle?: T;
  themeColor?: T;
  schemaOrgName?: T;
  schemaLocation?: T;
  schemaAlternateNames?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  footerTagline?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroHeadline?:
    | T
    | {
        word?: T;
        accent?: T;
        id?: T;
      };
  heroGhostText?: T;
  heroSubtitle?: T;
  heroCtaLabel?: T;
  heroCtaHref?: T;
  statMembersLabel?: T;
  statMembersValue?: T;
  statOrgsLabel?: T;
  statOrgsValue?: T;
  statTitlesLabel?: T;
  statTitlesValue?: T;
  statReachLabel?: T;
  statReachValue?: T;
  orgsKicker?: T;
  orgsTitle?: T;
  rosterKicker?: T;
  rosterTitle?: T;
  ctaEyebrow?: T;
  ctaTitle?: T;
  ctaPrimaryLabel?: T;
  ctaPrimaryHref?: T;
  ctaSecondaryLabel?: T;
  ctaSecondaryHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-event_select".
 */
export interface FeaturedEventSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  eventName?: T;
  dateRangeLabel?: T;
  location?: T;
  prize?: T;
  startsAt?: T;
  teamPrefix?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-intros_select".
 */
export interface PageIntrosSelect<T extends boolean = true> {
  players?:
    | T
    | {
        kicker?: T;
        title?: T;
        subtitle?: T;
      };
  orgs?:
    | T
    | {
        kicker?: T;
        title?: T;
        subtitle?: T;
      };
  ewc?:
    | T
    | {
        kicker?: T;
        subtitle?: T;
      };
  achievements?:
    | T
    | {
        kicker?: T;
        title?: T;
        subtitle?: T;
      };
  founders?:
    | T
    | {
        kicker?: T;
        title?: T;
      };
  about?:
    | T
    | {
        kicker?: T;
        title?: T;
        subtitle?: T;
        lead?: T;
        body?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}